# Generated by Django 5.0.1 on 2024-02-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paging", "0002_alter_category_options_product_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.FileField(default="", upload_to="images"),
        ),
    ]
