# Generated by Django 5.0.1 on 2024-02-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0003_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
