# Generated by Django 5.0.1 on 2024-02-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ordering", "0004_order_shipping_price"),
        ("paging", "0003_product_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="product",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="paging.product",
            ),
            preserve_default=False,
        ),
    ]
