# Generated by Django 5.0.1 on 2024-02-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cartfav", "0002_remove_cartitem_product_cartitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="shipping_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
